title: Ajwad Javed
description: <b>Reseacher</b>
logo: me.png
url: https://ajwadjaved.github.io/
title: Ajwad Javed

email: ajwad.bsaf18@nbs.nust.edu.pk
show_downloads: false
theme: jekyll-theme-minimal


