title: Ajwad Javed
description: Reseacher
title: cat /var/log/life
logo: me.png
url: https://ajwadjaved.github.io/

email: ajwad.bsaf18@nbs.nust.edu.pk
show_downloads: false
theme: jekyll-theme-minimal


