title: Ajwad Javed
description: <h1>Reseacher</h1>
logo: me.png
url: https://ajwadjaved.github.io/
title: Ajwad javed | Researcher

email: ajwad.bsaf18@nbs.nust.edu.pk
show_downloads: false
theme: jekyll-theme-minimal


