title: Tosikko
logo: /assets/img/logo.png
url: https://tosikko.github.io/


description: Researcher, contact at rand.bsaf18@nbs.nust.edu.pk
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal


