title: Tosikko
#logo: /assets/img/logo.png
logo: me.png
url: https://ajwadjaved.github.io/


description: Researcher, contact at ajwad.bsaf18@nbs.nust.edu.pk
show_downloads: false
theme: jekyll-theme-minimal


