title: Ajwad Javed
description: Personal Website
logo: me.png
url: https://ajwadjaved.github.io/

description: Researcher \| [Mail](mailto:ajwad.bsaf18@nbs.nust.edu.pk)
show_downloads: false
theme: jekyll-theme-minimal


